apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Service-with-docs
  description: service for using with documents
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  dependencyOf: #Optional Field
#    - component:default/artist-web-lookup
  providesApis:
    - artist-api
