apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web-lookup
  description: Search about artist
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
