apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Service-with-doc
  description: Example of creating a tecDocument
  annotations:
    backstage.io/tecdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
