apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Software-Development
  description: Software Development Department
spec:
  type: team
  children:
    - Production-Development
    - Infrastructure-Operations
    - Quality-Assurance
