# do allow 'Domain' type to be added in your backend app-config.yaml
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: artists
  description: Everything about artists
spec:
  owner: artist-relations-team
  subdomainOf: audio-domain
