apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dummy-api
  description: A dummy API for demonstration purposes
  tags:
    - rest
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: Team-Engineering
  definition: |
    openapi: 3.0.0
    info:
      title: Dummy API
      version: 1.0.0
      description: This is a dummy API for testing purposes.
    paths:
      /hello:
        get:
          summary: Returns a greeting message
          responses:
            "200":
              description: A successful response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Hello, world!"
