apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: quality-assurance
  description: The division ensuring the software meets quality standards.
spec:
  type: division
  parent: software-development
  children:
    - test-automation-team
    - manual-testing-team
